version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "deps"
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "deps"
