name: Docker release build

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tagName
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: |
          docker build . -t ${{ secrets.DOCKER_IMAGE_NAME }}:$GIT_TAG_NAME
      - name: docker tag latest
        run: |
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:$GIT_TAG_NAME ${{ secrets.DOCKER_IMAGE_NAME }}:latest
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:$GIT_TAG_NAME
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:latest
