name: Lint Code Base

on:
  push:

  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_PERL: false
          VALIDATE_RAKU: false
          VALIDATE_PHP: false
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_GO: false
          VALIDATE_CLOJURE: false
          VALIDATE_KOTLIN: false
          VALIDATE_DART: false
          VALIDATE_ANSIBLE: false
          DISABLE_ERRORS: ${{ secrets.LINT_DISABLE_ERRORS }}
          OUTPUT_FORMAT: tap
          OUTPUT_DETAILS: detailed

      - name: Upload Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /tmp/lint/super-linter.report
